# Generated by Django 5.1.7 on 2025-03-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_remove_country_on_shipment_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
